---
name: UI-E2E Test Cypress
on: 
  workflow_dispatch:
    inputs:
      test-tags:
        type: choice
        required: true
        default: 'critical'
        description: 'Select test tag'
        options:
        - critical
        - regression
        - regression_2_0
      environment:
        type: choice
        required: true
        default: 'https://uitest.test.medirecords.com/ui-automation/'
        description: 'Select test environment'
        options:
        - https://uitest.test.medirecords.com/ui-automation/

  workflow_call:
    inputs:
      test-tags:
        type: string
        required: true
      environment:
        type: string
        required: true

jobs:
  mrtest:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome]
        containers: [0,1,2,3,4]
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - uses: actions/checkout@v3

      - name: Run UI automation composite
        uses: ./.github/actions/test
        with:
          working-directory: test
          ENVIRONMENT: ${{inputs.environment}}
          TEST_TAGS: ${{inputs.test-tags}}
          MATRIX_CONTAINERS: ${{matrix.containers}}

        
      - name: Set current date as env variable
        run: echo "### report link https://admin-staging.aonewallet.com/  :" >> $GITHUB_STEP_SUMMARY