---
name: UI-E2E Test Cypress
on: 
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          runTests: false
  # lint:
  #   needs: install
  #   runs-on: ubuntu-latest
  #   container: cypress/browsers:node16.16.0-chrome107-ff107-edge
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: cypress-io/github-action@v5
  #       with:
  #         runTests: false
  #     - run: npm run lint
  mrtest:
    # needs: lint
    needs: install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome]
        containers: [0,1,2,3,4]
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          runTests: false
      - uses: cypress-io/github-action@v5
        with:
          install: false
          wait-on: 'https://admin-staging.aonewallet.com'
          browser: ${{ matrix.browser }}
          record: false
          parallel: false
          config: "baseUrl=https://admin-staging.aonewallet.com"
          command: npx ts-node scripts/cypress-ci-run.ts
        env:
          # the number of containers in the job matrix
          TOTAL_RUNNERS: 5
          THIS_RUNNER: ${{ matrix.containers }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Report
        if: always()
        run: npm run reports
      - name: Upload reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cucumber-reports
          path: cypress/test-reports/
      - name: Upload screenshots  
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: test/cypress/screenshots