---
name: UI-E2E Test Cypress
on: 
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          runTests: false
  mrtest:
    # needs: lint
    needs: install
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome]
        containers: [0,1,2,3,4]
    container: cypress/browsers:node16.16.0-chrome107-ff107-edge
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          runTests: false
          wait-on: 'https://admin-staging.aonewallet.com'
          browser: ${{ matrix.browser }}
          record: false
          parallel: false
      - run: >
          CYPRESS_BASE_URL=https://admin-staging.aonewallet.com/ npx cypress run 
          --env tags=@affiliates,jsonOutput=cypress/cucumber-json/cucumber-report_${{ matrix.containers }}.json 
          --spec $(npx ts-node scripts/cypress-spec-split.ts 5 ${{ matrix.containers }}) --browser ${{ matrix.browser }}
        id: build
        continue-on-error: true
        
      - name: Set current date as env variable
        if:  ${{steps.build.status == 'success'}}
        run: echo "### report link https://admin-staging.aonewallet.com/  :" >> $GITHUB_STEP_SUMMARY